var subject = require('./mystery.js')
var mock = require('mock-fs');
subject.inc(99,-77);
subject.inc(101,"junk");
subject.inc(99,"junk");
subject.inc(101,-77);
subject.inc(99,-77);
subject.inc(101,"junk");
subject.inc(99,'');
subject.inc(101,'');
subject.weird(100,10,32,"mode");
subject.weird(98,12,34,"junk");
subject.weird(100,12,34,"junk");
subject.weird(98,10,34,"junk");
subject.weird(98,12,32,"junk");
subject.weird(98,12,34,"mode");
subject.weird(98,10,32,"mode");
subject.weird(100,12,32,"mode");
subject.weird(100,10,34,"mode");
subject.weird(100,10,32,"junk");
subject.weird(100,10,34,"junk");
subject.weird(98,10,32,"junk");
subject.weird(98,12,32,"mode");
subject.weird(100,12,34,"mode");
subject.weird(100,12,34,"street");
subject.weird(98,10,34,"street");
subject.weird(98,12,32,"street");
subject.weird(100,10,32,"street");
subject.weird(100,10,34,"street");
subject.weird(98,10,32,"street");
subject.weird(100,12,34,"strictly");
subject.weird(98,10,34,"strictly");
subject.weird(98,12,32,"strictly");
subject.weird(100,10,32,"strictly");
subject.weird(100,10,34,"strictly");
subject.weird(98,10,32,"strictly");
subject.weird(98,12,34,"street");
subject.weird(98,12,34,"junk");
subject.weird(98,12,34,"strictly");
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file1','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file1','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('pathContent/file1','');
mock.restore();
mock({});
	subject.fileTest('pathContent/file1','');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file2','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file2','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('pathContent/file2','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('pathContent/file2','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({});
	subject.fileTest('pathContent/file1','path/fileExists');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file2','');
mock.restore();
mock({"pathContent":{"file1":"text content","file2":""}});
	subject.fileTest('pathContent/file2','');
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest('pathContent/file2','');
mock.restore();
mock({});
	subject.fileTest('pathContent/file2','');
mock.restore();
subject.normalize('');
subject.normalize('');
subject.normalize('');
subject.format('','',{"strongbow":true});
subject.format('','',{"strongbow":false});
subject.format('','',{"strongbow":false});
subject.format('','',{"strongbow":true});
subject.blackListNumber("211-919-9191");
subject.blackListNumber("212-919-9191");
subject.blackListNumber("211-919-9191");
subject.blackListNumber("212-919-9191");
